In [1]:
import numpy as np
import pandas as pd
import yaml
from sqlalchemy import create_engine

#### Conexion con las bases de datos

In [ ]:
config = {
    'host': 'localhost',       
    'port': 
    'database': 'mensajeria',  
    'user': 'postgres',            
    'password': 
}

In [3]:
with open("../config.yml", "r") as f:
    config = yaml.safe_load(f)

    config_co = config['SOURCE_DB']
    config_etl = config['ETL_PRO']

url_co = f"{config_co['drivername']}://{config_co['user']}:{config_co['password']}@{config_co['host']}:{config_co['port']}/{config_co['dbname']}"
url_etl = f"{config_etl['drivername']}://{config_etl['user']}:{config_etl['password']}@{config_etl['host']}:{config_etl['port']}/{config_etl['dbname']}"


engine_origen = create_engine(url_co)
engine_destino = create_engine(url_etl)

In [ ]:
tipo_novedad = pd.read_sql_table("mensajeria_tiponovedad", engine_origen)

In [6]:
tipo_novedad.head()

   id                  nombre
0   2      No puedo continuar
1   1  Novedades del servicio

In [10]:
dim_novedad = tipo_novedad.copy()

In [11]:
dim_novedad.rename(columns={
    'id': 'id_tipo_novedad',
    'nombre': 'tipo_novedad'
}, inplace=True)

In [12]:
dim_novedad.columns.tolist()

['id_tipo_novedad', 'tipo_novedad']

In [14]:
columnas_necesarias = ["id_tipo_novedad", "tipo_novedad"]
dim_novedad = dim_novedad[columnas_necesarias].copy()
dim_novedad.head()

   id_tipo_novedad            tipo_novedad
0                2      No puedo continuar
1                1  Novedades del servicio

In [15]:
dim_novedad.to_sql('dim_novedad',con=engine_destino,if_exists='replace',index_label='key_dim_novedad')

2