In [1]:
import numpy as np
import pandas as pd
import yaml
from sqlalchemy import create_engine

#### Conexion con las bases de datos

In [2]:
with open('../config.yml', 'r') as f:
    config = yaml.safe_load(f)
    config_co = config['mensajeria_bd']
    config_etl = config['etl_mensajeria']
    
url_co = (f"{config_co['drivername']}://{config_co['user']}:{config_co['password']}@{config_co['host']}:"
          f"{config_co['port']}/{config_co['dbname']}")
url_etl = (f"{config_etl['drivername']}://{config_etl['user']}:{config_etl['password']}@{config_etl['host']}:"
           f"{config_etl['port']}/{config_etl['dbname']}")

engine_origen = create_engine(url_co)
engine_destino = create_engine(url_etl)

In [3]:
dim_hora = pd.DataFrame({
    "id_hora": range(24),
    "hora": range(24)
})
dim_hora.head()

   id_hora  hora
0        0     0
1        1     1
2        2     2
3        3     3
4        4     4

In [ ]:
dim_hora.to_sql('dim_hora',con=engine_destino,if_exists='replace',index_label='key_dim_hora')
dim_hora.head()

       fecha   año  mes  dia  dia_semana  fin_de_semana
0 2023-09-19  2023    9   19           1              0
1 2023-09-20  2023    9   20           2              0
2 2023-09-21  2023    9   21           3              0
3 2023-09-22  2023    9   22           4              0
4 2023-09-23  2023    9   23           5              1