In [1]:
import numpy as np
import pandas as pd
import yaml
from sqlalchemy import create_engine

In [ ]:
config = {
    'host': 'localhost',       
    'port': 
    'database': 'mensajeria',  
    'user': 'postgres',            
    'password': 
}

In [3]:
with open("../config.yml", "r") as f:
    config = yaml.safe_load(f)

    config_co = config['SOURCE_DB']
    config_etl = config['ETL_PRO']

url_co = f"{config_co['drivername']}://{config_co['user']}:{config_co['password']}@{config_co['host']}:{config_co['port']}/{config_co['dbname']}"
url_etl = f"{config_etl['drivername']}://{config_etl['user']}:{config_etl['password']}@{config_etl['host']}:{config_etl['port']}/{config_etl['dbname']}"


engine_origen = create_engine(url_co)
engine_destino = create_engine(url_etl)

In [4]:
dim_mensajero = pd.read_sql_table("clientes_mensajeroaquitoy", engine_origen)
dim_mensajero.head()

,id,user_id,activo,fecha_entrada,fecha_salida,salario,telefono,ciudad_operacion_id,token_Firebase,url_foto
0,1,2,True,NaT,NaT,NaN,310-300000,13.0,NaN,http:
1,42,410,True,NaT,NaT,NaN,310-300000,1.0,NaN,http:
2,48,447,True,2024-07-12,NaT,1300000.0,310-300000,1.0,NaN,http:
3,41,400,True,NaT,NaT,NaN,310-300000,1.0,NaN,http:
4,13,331,True,2021-11-08,NaT,1160000.0,310-300000,4.0,NaN,http:

In [5]:
dim_mensajero.rename(
    columns={
        "id": "id_mensajero",
    },
    inplace=True,
)

In [6]:
dim_mensajero.columns.tolist()

['id_mensajero',
 'user_id',
 'activo',
 'fecha_entrada',
 'fecha_salida',
 'salario',
 'telefono',
 'ciudad_operacion_id',
 'token_Firebase',
 'url_foto']

In [7]:
columnas_necesarias = ["id_mensajero","activo"]
dim_mensajero = dim_mensajero[columnas_necesarias].copy()
dim_mensajero.head()

   id_mensajero  activo
0             1    True
1            42    True
2            48    True
3            41    True
4            13    True

In [8]:
dim_mensajero.to_sql(
    "dim_mensajero",
    con=engine_destino,
    if_exists="replace",
    index_label="key_dim_mensajero",
)

50