In [1]:
import numpy as np
import pandas as pd
import yaml
from sqlalchemy import create_engine

In [2]:
# 1. Cargar el archivo de configuración
with open("../config.yml", "r") as f:
    config = yaml.safe_load(f)

config_co = config["SOURCE_DB"]  # Tu origen (bd_oltp)
config_etl = config["TARGET_DB"]  # Tu destino (bd_bodega)

# 3. Crear las URLs de conexión (El resto del código se queda igual)
url_co = f"{config_co['drivername']}://{config_co['user']}:{config_co['password']}@{config_co['host']}:{config_co['port']}/{config_co['dbname']}"
url_etl = f"{config_etl['drivername']}://{config_etl['user']}:{config_etl['password']}@{config_etl['host']}:{config_etl['port']}/{config_etl['dbname']}"

# 4. Crear los motores de conexión
engine_origen = create_engine(url_co)
engine_destino = create_engine(url_etl)

In [3]:
mensajero = pd.read_sql_table("clientes_datosmensajero", engine_origen)
mensajero.head()

   datos_id
0         1
1         2
2         3

In [4]:
mensajero.rename(
    columns={
        "datos_id": "id_mensajero",
        # Se pueden agregar luego mas columnas, igual no hay xd
    },
    inplace=True,
)

columnas_necesarias = ["id_mensajero"]  # ampliar cuando veas las columnas reales
dim_mensajero = mensajero[columnas_necesarias].copy()
dim_mensajero.head()

   id_mensajero
0             1
1             2
2             3

In [5]:
dim_mensajero.to_sql(
    "dim_mensajero",
    con=engine_destino,
    if_exists="replace",
    index_label="key_dim_mensajero",
)

3