In [6]:
import numpy as np
import pandas as pd
import yaml
from sqlalchemy import create_engine

#### Conexion con las bases de datos

In [8]:
with open('../config.yml', 'r') as f:
    config = yaml.safe_load(f)
    config_co = config['SOURCE_DB']
    config_etl = config['ETL_PRO']
    
url_co = (f"{config_co['drivername']}://{config_co['user']}:{config_co['password']}@{config_co['host']}:"
          f"{config_co['port']}/{config_co['dbname']}")
url_etl = (f"{config_etl['drivername']}://{config_etl['user']}:{config_etl['password']}@{config_etl['host']}:"
           f"{config_etl['port']}/{config_etl['dbname']}")

engine_origen = create_engine(url_co)
engine_destino = create_engine(url_etl)

In [9]:
estado = pd.read_sql_table("mensajeria_estado", engine_origen)

In [10]:
estado.head()

   id                  nombre             descripcion
0   4  Recogido por mensajero  Recogido por mensajero
1   5    Entregado en destino    Entregado en destino
2   3             Con novedad           Tiene novedad
3   6      Terminado completo      Terminado completo
4   1                Iniciado   Creado por el usuario

In [11]:
estado.rename(columns={
    'id': 'id_estado'
}, inplace=True)

In [12]:
columnas_necesarias = ["id_estado", "nombre", "descripcion"]
dim_estado= estado[columnas_necesarias].copy()
dim_estado.head()

   id_estado                  nombre             descripcion
0          4  Recogido por mensajero  Recogido por mensajero
1          5    Entregado en destino    Entregado en destino
2          3             Con novedad           Tiene novedad
3          6      Terminado completo      Terminado completo
4          1                Iniciado   Creado por el usuario

In [13]:
dim_estado.to_sql('dim_estado',con=engine_destino,if_exists='replace',index_label='key_dim_estado')

6